{
    "sourceFile": "src/services/authService.js",
    "activeCommit": 0,
    "commits": [
        {
            "activePatchIndex": 12,
            "patches": [
                {
                    "date": 1752586035008,
                    "content": "Index: \n===================================================================\n--- \n+++ \n"
                },
                {
                    "date": 1752586042337,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -12,11 +12,9 @@\n         }\r\n     },\r\n     loginUser: async (credentials) => {\r\n       try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, {\r\n-          \r\n-        });\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, );\r\n \r\n         return response.data;\r\n       } catch (error) {\r\n         throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n"
                },
                {
                    "date": 1752586049514,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,24 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+    sent_password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during check-in:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    loginUser: async (credentials) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credetials);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n+      }\r\n+    },\r\n+\r\n+}\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833376663,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -6,43 +6,40 @@\n         try {\r\n         const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n         return response.data;\r\n         } catch (error) {\r\n-        console.error(\"Error during check-in:\", error);\r\n+        console.error(\"Error during sent email:\", error);\r\n         throw error;\r\n         }\r\n     },\r\n-    loginUser: async (credentials) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, credetials);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n-      }\r\n-    },\r\n-\r\n-}\n-import { API_ENDPOINTS } from \"../utils/constants\";\r\n-import api from \"./api\";\r\n-\r\n-export const authService = {\r\n-    sent_password_reset: async (formData) => {\r\n+    password_reset: async (formData) => {\r\n         try {\r\n         const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n         return response.data;\r\n         } catch (error) {\r\n-        console.error(\"Error during check-in:\", error);\r\n+        console.error(\"Error during reset password:\", error);\r\n         throw error;\r\n         }\r\n     },\r\n     loginUser: async (credentials) => {\r\n       try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, );\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n \r\n         return response.data;\r\n       } catch (error) {\r\n         throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n       }\r\n     },\r\n \r\n+    \r\n+\r\n+    changePassword: async (formData) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n+      }\r\n+    }\r\n+\r\n }\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833383852,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,45 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+    sent_password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during sent email:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during reset password:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    loginUser: async (credentials) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n+      }\r\n+    },\r\n+\r\n+    logoutUser\r\n+\r\n+    changePassword: async (formData) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n+      }\r\n+    }\r\n+\r\n+}\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833391542,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -29,9 +29,9 @@\n         throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n       }\r\n     },\r\n \r\n-    logoutUser\r\n+    logoutUser : ()\r\n \r\n     changePassword: async (formData) => {\r\n       try {\r\n         const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n@@ -41,50 +41,5 @@\n         throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n       }\r\n     }\r\n \r\n-}\n-import { API_ENDPOINTS } from \"../utils/constants\";\r\n-import api from \"./api\";\r\n-\r\n-export const authService = {\r\n-    sent_password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during sent email:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during reset password:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    loginUser: async (credentials) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n-      }\r\n-    },\r\n-\r\n-    \r\n-\r\n-    changePassword: async (formData) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n-      }\r\n-    }\r\n-\r\n }\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833397873,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,45 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+    sent_password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during sent email:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during reset password:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    loginUser: async (credentials) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n+      }\r\n+    },\r\n+\r\n+    logoutUser : (){},\r\n+\r\n+    changePassword: async (formData) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n+      }\r\n+    }\r\n+\r\n+}\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833404139,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,45 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+    sent_password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during sent email:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during reset password:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    loginUser: async (credentials) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n+      }\r\n+    },\r\n+\r\n+    logoutUser : () {},\r\n+\r\n+    changePassword: async (formData) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n+      }\r\n+    }\r\n+\r\n+}\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833413366,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,47 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+    sent_password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during sent email:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    password_reset: async (formData) => {\r\n+        try {\r\n+        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n+        return response.data;\r\n+        } catch (error) {\r\n+        console.error(\"Error during reset password:\", error);\r\n+        throw error;\r\n+        }\r\n+    },\r\n+    loginUser: async (credentials) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n+      }\r\n+    },\r\n+\r\n+    logoutUser : () => {\r\n+      \r\n+    },\r\n+\r\n+    changePassword: async (formData) => {\r\n+      try {\r\n+        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+        return response.data;\r\n+      } catch (error) {\r\n+        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n+      }\r\n+    }\r\n+\r\n+}\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833418799,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -30,56 +30,20 @@\n       }\r\n     },\r\n \r\n     logoutUser : () => {\r\n-      \r\n-    },\r\n+      localStorage.removeItem(\"accessToken\");\r\n+  localStorage.removeItem(\"refreshToken\");\r\n+  localStorage.removeItem(\"userInfo\");\r\n+  localStorage.removeItem(\"userRole\");\r\n \r\n-    changePassword: async (formData) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+  // Optional: clear everything\r\n+  // localStorage.clear();\r\n \r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n-      }\r\n-    }\r\n-\r\n-}\n-import { API_ENDPOINTS } from \"../utils/constants\";\r\n-import api from \"./api\";\r\n-\r\n-export const authService = {\r\n-    sent_password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during sent email:\", error);\r\n-        throw error;\r\n-        }\r\n+  // Redirect to login\r\n+  window.location.href = \"/login\";\r\n     },\r\n-    password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during reset password:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    loginUser: async (credentials) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n \r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n-      }\r\n-    },\r\n-\r\n-    logoutUser : () {},\r\n-\r\n     changePassword: async (formData) => {\r\n       try {\r\n         const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n \r\n@@ -88,95 +52,5 @@\n         throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n       }\r\n     }\r\n \r\n-}\n-import { API_ENDPOINTS } from \"../utils/constants\";\r\n-import api from \"./api\";\r\n-\r\n-export const authService = {\r\n-    sent_password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during sent email:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during reset password:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    loginUser: async (credentials) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n-      }\r\n-    },\r\n-\r\n-    logoutUser : (){},\r\n-\r\n-    changePassword: async (formData) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n-      }\r\n-    }\r\n-\r\n-}\n-import { API_ENDPOINTS } from \"../utils/constants\";\r\n-import api from \"./api\";\r\n-\r\n-export const authService = {\r\n-    sent_password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during sent email:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    password_reset: async (formData) => {\r\n-        try {\r\n-        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n-        return response.data;\r\n-        } catch (error) {\r\n-        console.error(\"Error during reset password:\", error);\r\n-        throw error;\r\n-        }\r\n-    },\r\n-    loginUser: async (credentials) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n-      }\r\n-    },\r\n-\r\n-    logoutUser : ()\r\n-\r\n-    changePassword: async (formData) => {\r\n-      try {\r\n-        const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n-\r\n-        return response.data;\r\n-      } catch (error) {\r\n-        throw error.response?.data || { message: 'Password change failed. Please try again.' };\r\n-      }\r\n-    }\r\n-\r\n }\n\\ No newline at end of file\n"
                },
                {
                    "date": 1752833427633,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,67 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+  sent_password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during sent email:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during reset password:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  loginUser: async (credentials) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || { message: \"Login failed. Please try again.\" }\r\n+      );\r\n+    }\r\n+  },\r\n+\r\n+  logoutUser: () => {\r\n+    localStorage.removeItem(\"accessToken\");\r\n+    localStorage.removeItem(\"refreshToken\");\r\n+    localStorage.removeItem(\"userInfo\");\r\n+    localStorage.removeItem(\"userRole\");\r\n+\r\n+    // Optional: clear everything\r\n+    // localStorage.clear();\r\n+\r\n+    // Redirect to login\r\n+    window.location.href = \"/login\";\r\n+  },\r\n+\r\n+  changePassword: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || {\r\n+          message: \"Password change failed. Please try again.\",\r\n+        }\r\n+      );\r\n+    }\r\n+  },\r\n+};\r\n"
                },
                {
                    "date": 1752833434384,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,66 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+  sent_password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during sent email:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during reset password:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  loginUser: async (credentials) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || { message: \"Login failed. Please try again.\" }\r\n+      );\r\n+    }\r\n+  },\r\n+\r\n+  logoutUser: () => {\r\n+    localStorage.removeItem(\"accessToken\");\r\n+    localStorage.removeItem(\"refreshToken\");\r\n+    localStorage.removeItem(\"userInfo\");\r\n+    localStorage.removeItem(\"userRole\");\r\n+\r\n+    // localStorage.clear();\r\n+\r\n+    // Redirect to login\r\n+    window.location.href = \"/login\";\r\n+  },\r\n+\r\n+  changePassword: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || {\r\n+          message: \"Password change failed. Please try again.\",\r\n+        }\r\n+      );\r\n+    }\r\n+  },\r\n+};\r\n"
                },
                {
                    "date": 1752833440495,
                    "content": "Index: \n===================================================================\n--- \n+++ \n@@ -0,0 +1,66 @@\n+import { API_ENDPOINTS } from \"../utils/constants\";\r\n+import api from \"./api\";\r\n+\r\n+export const authService = {\r\n+  sent_password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during sent email:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  password_reset: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(\r\n+        API_ENDPOINTS.SENT_PASSWORD_RESET,\r\n+        formData\r\n+      );\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      console.error(\"Error during reset password:\", error);\r\n+      throw error;\r\n+    }\r\n+  },\r\n+  loginUser: async (credentials) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.LOGIN, credentials);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || { message: \"Login failed. Please try again.\" }\r\n+      );\r\n+    }\r\n+  },\r\n+\r\n+  logoutUser: () => {\r\n+    localStorage.removeItem(\"accessToken\");\r\n+    localStorage.removeItem(\"refreshToken\");\r\n+    localStorage.removeItem(\"userInfo\");\r\n+    localStorage.removeItem(\"userRole\");\r\n+\r\n+    // localStorage.clear();\r\n+\r\n+    // Redirect to login\r\n+    window.location.href = \"/loginform\";\r\n+  },\r\n+\r\n+  changePassword: async (formData) => {\r\n+    try {\r\n+      const response = await api.post(API_ENDPOINTS.CHANGE_PASSWORD, formData);\r\n+\r\n+      return response.data;\r\n+    } catch (error) {\r\n+      throw (\r\n+        error.response?.data || {\r\n+          message: \"Password change failed. Please try again.\",\r\n+        }\r\n+      );\r\n+    }\r\n+  },\r\n+};\r\n"
                }
            ],
            "date": 1752586035008,
            "name": "Commit-0",
            "content": "import { API_ENDPOINTS } from \"../utils/constants\";\r\nimport api from \"./api\";\r\n\r\nexport const authService = {\r\n    sent_password_reset: async (formData) => {\r\n        try {\r\n        const response = await api.post(API_ENDPOINTS.SENT_PASSWORD_RESET, formData);\r\n        return response.data;\r\n        } catch (error) {\r\n        console.error(\"Error during check-in:\", error);\r\n        throw error;\r\n        }\r\n    },\r\n    loginUser: async (credentials) => {\r\n      try {\r\n        const response = await api.post(API_ENDPOINTS.LOGIN, {\r\n          \r\n        });\r\n\r\n        return response.data;\r\n      } catch (error) {\r\n        throw error.response?.data || { message: 'Login failed. Please try again.' };\r\n      }\r\n    },\r\n\r\n}"
        }
    ]
}